# Book settings
title: Object Recognition Lecture
author: Prof. Dr. Johannes Maucher
logo: hdmlogomed.jpg

bibtex_bibfiles:
  - cvReferences.bib

parse:
  myst_extended_syntax: true

latex:
  latex_documents:
    targetname: or.tex



