# Book settings
title: Object Recognition Lecture
author: Prof. Dr. Johannes Maucher
logo: hdmlogomed.jpg

only_build_toc_files: true

bibtex_bibfiles:
  - cvReferences.bib

parse:
  myst_extended_syntax: true

latex:
  latex_documents:
    targetname: or.tex

html:
  only_build_toc_files: true

execute:
  execute_notebooks: 'off'